'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type Client = { id: string; full_name: string; email?: string; telegram_username?: string; phone?: string; country?: string; plan: string; status: string; notes?: string; created_at: string };
type License = { id: string; client_id: string; license_key: string; platform: string; account_number?: string; plan: string; status: string; issued_at: string; expires_at?: string };
type Payment = { id: string; client_id: string; method: string; status: string; amount: number; currency: string; payment_date?: string; reference_id?: string; notes?: string; created_at: string };
type Activity = { id: string; client_id: string; action: string; details?: string; actor_email?: string; created_at: string };
type Data = { clients: Client[]; licenses: License[]; payments: Payment[]; activity: Activity[]; metrics: { totalClients: number; activeClients: number; expiringLicenses: number; pendingPayments: number; revenueToday: number; revenueMonth: number } };
const empty: Data = { clients: [], licenses: [], payments: [], activity: [], metrics: { totalClients: 0, activeClients: 0, expiringLicenses: 0, pendingPayments: 0, revenueToday: 0, revenueMonth: 0 } };

export default function BusinessDashboard({ section, canWrite }: { section: string; canWrite: boolean }) {
  const [data, setData] = useState<Data>(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Client | null>(null); const [modal, setModal] = useState<'client'|'license'|'payment'|null>(null);
  const load = useCallback(async () => { setLoading(true); const response = await fetch('/api/business', { cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (response.ok) { setData(payload); setError(''); } else setError(payload.error || 'Unable to load Phase 3'); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  const clients = useMemo(() => data.clients.filter((row) => `${row.full_name} ${row.email || ''} ${row.telegram_username || ''} ${row.country || ''}`.toLowerCase().includes(search.toLowerCase())), [data.clients, search]);
  const clientName = (id: string) => data.clients.find((client) => client.id === id)?.full_name || 'Unknown client';
  const openCreate = (type: 'client'|'license'|'payment', client?: Client) => { setSelected(client || null); setModal(type); };
  if (loading) return <div className="business-loading"><span /> Loading secure client records…</div>;
  if (error) return <article className="panel migration-notice"><p className="eyebrow">Database setup required</p><h2>Apply the Phase 3 migration</h2><p className="muted">{error}</p><code>supabase/migrations/20260716_orion_business.sql</code></article>;
  return <>
    {section === 'sales' && <SalesOverview data={data} />}
    {section === 'clients' && <><BusinessToolbar title="Client management" subtitle="Customer profiles, plans, payment history and activity." search={search} setSearch={setSearch} action="Add client" onAction={canWrite ? () => openCreate('client') : undefined} exportType="clients" /><div className="client-grid">{clients.map((client) => <ClientCard key={client.id} client={client} licenses={data.licenses.filter((row) => row.client_id === client.id)} payments={data.payments.filter((row) => row.client_id === client.id)} onOpen={() => setSelected(client)} />)}{!clients.length && <Empty text="No clients match this search." />}</div></>}
    {section === 'licenses' && <><BusinessToolbar title="License manager" subtitle="Generate, monitor and manage Orion MT4/MT5 licenses." action="Generate license" onAction={canWrite && data.clients.length ? () => openCreate('license') : undefined} exportType="licenses" /><LicenseTable rows={data.licenses} clientName={clientName} /></>}
    {section === 'payments' && <><BusinessToolbar title="Manual payments" subtitle="Store payment records only. No gateway or automatic charge is connected." action="Record payment" onAction={canWrite && data.clients.length ? () => openCreate('payment') : undefined} exportType="payments" /><PaymentTable rows={data.payments} clientName={clientName} /></>}
    {section === 'activity' && <><BusinessToolbar title="Client activity" subtitle="A chronological audit trail of client, license and payment changes." /><ActivityList rows={data.activity} clientName={clientName} /></>}
    {selected && !modal && <ClientProfile client={selected} licenses={data.licenses.filter((row) => row.client_id === selected.id)} payments={data.payments.filter((row) => row.client_id === selected.id)} activity={data.activity.filter((row) => row.client_id === selected.id)} canWrite={canWrite} close={() => setSelected(null)} addLicense={() => openCreate('license', selected)} addPayment={() => openCreate('payment', selected)} />}
    {modal && <RecordModal type={modal} clients={data.clients} selected={selected} close={() => setModal(null)} saved={async () => { setModal(null); setSelected(null); await load(); }} />}
  </>;
}

function SalesOverview({ data }: { data: Data }) { const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value); const planCounts = ['Basic','Premium','Lifetime'].map((plan) => ({ plan, value: data.clients.filter((row) => row.plan === plan).length })); const max = Math.max(1, ...planCounts.map((row) => row.value)); return <><div className="business-kpis"><BizMetric label="Total clients" value={data.metrics.totalClients} note={`${data.metrics.activeClients} active`} color="blue" /><BizMetric label="Revenue today" value={money(data.metrics.revenueToday)} note="Paid + verified" color="green" /><BizMetric label="Revenue this month" value={money(data.metrics.revenueMonth)} note="Manual records" color="gold" /><BizMetric label="Pending payments" value={data.metrics.pendingPayments} note="Needs review" color="orange" /><BizMetric label="Expiring soon" value={data.metrics.expiringLicenses} note="Within 30 days" color="purple" /></div><div className="business-overview"><article className="panel business-panel"><p className="eyebrow">Portfolio</p><h2>Clients by plan</h2><div className="plan-bars">{planCounts.map((row) => <div key={row.plan}><span>{row.plan}<b>{row.value}</b></span><i><em style={{ width: `${row.value / max * 100}%` }} /></i></div>)}</div></article><article className="panel business-panel"><p className="eyebrow">Recent business activity</p><h2>Latest changes</h2><ActivityList rows={data.activity.slice(0, 6)} clientName={(id) => data.clients.find((row) => row.id === id)?.full_name || 'Client'} embedded /></article></div><PaymentTable rows={data.payments.slice(0, 8)} clientName={(id) => data.clients.find((row) => row.id === id)?.full_name || 'Client'} compact /></>; }
function BizMetric({ label, value, note, color }: { label: string; value: string|number; note: string; color: string }) { return <article className={`metric-card biz-metric ${color}`}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
function BusinessToolbar({ title, subtitle, search, setSearch, action, onAction, exportType }: { title: string; subtitle: string; search?: string; setSearch?: (v:string)=>void; action?: string; onAction?: ()=>void; exportType?: string }) { return <div className="business-toolbar"><div><p className="eyebrow">Orion operations</p><h2>{title}</h2><p className="muted">{subtitle}</p></div><div className="business-actions">{setSearch && <input aria-label="Search clients" placeholder="Search clients…" value={search} onChange={(event) => setSearch(event.target.value)} />}{exportType && <a className="glass-button" href={`/api/business/export?type=${exportType}`}>Export CSV</a>}{onAction && <button className="gold-button" onClick={onAction}>＋ {action}</button>}</div></div>; }
function ClientCard({ client, licenses, payments, onOpen }: { client: Client; licenses: License[]; payments: Payment[]; onOpen: ()=>void }) { const paid = payments.filter((row) => ['Paid','Manually verified'].includes(row.status)).reduce((sum, row) => sum + Number(row.amount), 0); return <button className="panel client-card" onClick={onOpen}><div className="client-card-top"><span className="client-avatar">{client.full_name.split(' ').map((part) => part[0]).slice(0,2).join('').toUpperCase()}</span><Status value={client.status} /></div><h3>{client.full_name}</h3><p>{client.email || client.telegram_username || 'No contact added'}</p><div className="client-card-meta"><span><small>Plan</small>{client.plan}</span><span><small>Licenses</small>{licenses.length}</span><span><small>Paid</small>${paid.toLocaleString()}</span></div></button>; }
function LicenseTable({ rows, clientName }: { rows: License[]; clientName: (id:string)=>string }) { return <article className="panel table-panel full business-table"><div className="data-table"><div className="table-head license-head"><span>Client</span><span>License</span><span>Platform</span><span>Account</span><span>Expiry</span><span>Status</span></div>{rows.map((row) => <div className="table-row license-row" key={row.id}><strong>{clientName(row.client_id)}</strong><code>{row.license_key}</code><span>{row.platform}</span><span>{row.account_number || '—'}</span><time>{row.expires_at ? new Date(row.expires_at).toLocaleDateString() : 'Lifetime'}</time><Status value={row.status} /></div>)}{!rows.length && <Empty text="No licenses created yet." />}</div></article>; }
function PaymentTable({ rows, clientName, compact=false }: { rows: Payment[]; clientName:(id:string)=>string; compact?: boolean }) { return <article className={`panel table-panel full business-table ${compact ? 'compact' : ''}`}><div className="data-table"><div className="table-head payment-head"><span>Client</span><span>Method</span><span>Amount</span><span>Date</span><span>Reference</span><span>Status</span></div>{rows.map((row) => <div className="table-row payment-row" key={row.id}><strong>{clientName(row.client_id)}</strong><span>{row.method}</span><span>{row.currency} {Number(row.amount).toLocaleString()}</span><time>{row.payment_date ? new Date(`${row.payment_date}T00:00:00`).toLocaleDateString() : '—'}</time><code>{row.reference_id || '—'}</code><Status value={row.status} /></div>)}{!rows.length && <Empty text="No payment records yet." />}</div></article>; }
function ActivityList({ rows, clientName, embedded=false }: { rows: Activity[]; clientName:(id:string)=>string; embedded?:boolean }) { const content = <div className="activity-list">{rows.map((row) => <div className="activity-item" key={row.id}><i /><div><strong>{row.action}</strong><span>{clientName(row.client_id)} · {row.details || 'Record updated'}</span><small>{new Date(row.created_at).toLocaleString()} {row.actor_email ? `· ${row.actor_email}` : ''}</small></div></div>)}{!rows.length && <Empty text="No activity recorded yet." />}</div>; return embedded ? content : <article className="panel activity-panel">{content}</article>; }
function Status({ value }: { value: string }) { return <span className={`record-status ${value.toLowerCase().replace(/\s/g,'-')}`}>{value}</span>; }
function Empty({ text }: { text: string }) { return <p className="empty-state business-empty">{text}</p>; }

function ClientProfile({ client, licenses, payments, activity, canWrite, close, addLicense, addPayment }: { client:Client; licenses:License[]; payments:Payment[]; activity:Activity[]; canWrite:boolean; close:()=>void; addLicense:()=>void; addPayment:()=>void }) { return <div className="modal-backdrop" onMouseDown={close}><section className="profile-drawer" onMouseDown={(e)=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><div className="profile-hero"><span className="client-avatar large">{client.full_name.slice(0,2).toUpperCase()}</span><div><p className="eyebrow">Client profile</p><h2>{client.full_name}</h2><p>{client.email || 'No email'} · {client.country || 'Country not set'}</p></div><Status value={client.status} /></div><div className="profile-facts"><span><small>Plan</small>{client.plan}</span><span><small>Telegram</small>{client.telegram_username || '—'}</span><span><small>Phone</small>{client.phone || '—'}</span><span><small>Joined</small>{new Date(client.created_at).toLocaleDateString()}</span></div>{canWrite && <div className="profile-actions"><button className="gold-button" onClick={addLicense}>＋ License</button><button className="glass-button" onClick={addPayment}>＋ Payment</button></div>}<h3>Licenses</h3><LicenseTable rows={licenses} clientName={()=>client.full_name} /><h3>Payments</h3><PaymentTable rows={payments} clientName={()=>client.full_name} /><h3>Activity timeline</h3><ActivityList rows={activity} clientName={()=>client.full_name} embedded />{client.notes && <div className="profile-notes"><small>Internal notes</small><p>{client.notes}</p></div>}</section></div>; }

function RecordModal({ type, clients, selected, close, saved }: { type:'client'|'license'|'payment'; clients:Client[]; selected:Client|null; close:()=>void; saved:()=>void }) { const [saving,setSaving]=useState(false); const [error,setError]=useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); const response = await fetch('/api/business',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resource:type,data})}); const payload=await response.json().catch(()=>({})); if(!response.ok){setError(payload.error||'Unable to save');setSaving(false);return;} await saved(); } return <div className="modal-backdrop" onMouseDown={close}><form className="record-modal" onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">New {type}</p><h2>{type==='client'?'Add a client':type==='license'?'Generate a license':'Record a payment'}</h2>{type==='client'?<ClientFields/>:type==='license'?<LicenseFields clients={clients} selected={selected}/>:<PaymentFields clients={clients} selected={selected}/>} {error&&<p className="form-error">{error}</p>}<button className="gold-button modal-submit" disabled={saving}>{saving?'Saving…':'Save record'}</button></form></div>; }
function ClientFields(){return <div className="form-grid"><Field label="Full name" name="full_name" required/><Field label="Email" name="email" type="email"/><Field label="Telegram username" name="telegram_username"/><Field label="Phone" name="phone"/><Field label="Country" name="country"/><Select label="Plan" name="plan" options={['Basic','Premium','Lifetime']}/><Select label="Status" name="status" options={['Active','Expired','Suspended']}/><label className="wide"><span>Notes</span><textarea name="notes" rows={4}/></label></div>}
function LicenseFields({clients,selected}:{clients:Client[];selected:Client|null}){return <div className="form-grid"><ClientSelect clients={clients} selected={selected}/><Field label="License key" name="license_key" defaultValue={`ORN-${crypto.randomUUID().slice(0,8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`} required/><Select label="Platform" name="platform" options={['MT5','MT4']}/><Field label="Account number" name="account_number"/><Select label="Plan" name="plan" options={['Basic','Premium','Lifetime']}/><Select label="Status" name="status" options={['Active','Expired','Suspended']}/><Field label="Expiry date" name="expires_at" type="date"/></div>}
function PaymentFields({clients,selected}:{clients:Client[];selected:Client|null}){return <div className="form-grid"><ClientSelect clients={clients} selected={selected}/><Select label="Payment method" name="method" options={['Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']}/><Select label="Payment status" name="status" options={['Pending','Paid','Manually verified','Failed','Refunded','Disputed']}/><Field label="Amount" name="amount" type="number" defaultValue="0" required/><Field label="Currency" name="currency" defaultValue="USD" required/><Field label="Payment date" name="payment_date" type="date"/><Field label="Transaction / reference ID" name="reference_id"/><label className="wide"><span>Notes</span><textarea name="notes" rows={3}/></label></div>}
function ClientSelect({clients,selected}:{clients:Client[];selected:Client|null}){return <label className="wide"><span>Client</span><select name="client_id" defaultValue={selected?.id} required>{clients.map((client)=><option key={client.id} value={client.id}>{client.full_name}</option>)}</select></label>}
function Field({label,name,type='text',required=false,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string}){return <label><span>{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue}/></label>}
function Select({label,name,options}:{label:string;name:string;options:string[]}){return <label><span>{label}</span><select name={name}>{options.map((option)=><option key={option}>{option}</option>)}</select></label>}
