'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { countryFlag, countryLabel } from '@/lib/country';

type Client = { id:string; auth_user_id?:string; full_name:string; email?:string; telegram_username?:string; phone?:string; country?:string; plan:string; status:string; notes?:string; created_at:string };
type License = { id:string; client_id:string; license_key:string; platform:string; account_number?:string; plan:string; status:string; issued_at:string; expires_at?:string };
type Payment = { id:string; client_id:string; license_id?:string; plan:string; method:string; status:string; amount:number; currency:string; payment_date?:string; reference_id?:string; notes?:string; created_at:string };
type Activity = { id:string; client_id:string; action:string; details?:string; actor_email?:string; created_at:string };
type Resource = 'client'|'license'|'payment';
type RecordValue = Client|License|Payment;
type Data = { clients:Client[]; licenses:License[]; payments:Payment[]; activity:Activity[]; metrics:{ totalClients:number; activeClients:number; expiringLicenses:number; pendingPayments:number; revenueToday:number; revenueMonth:number } };
const empty:Data={clients:[],licenses:[],payments:[],activity:[],metrics:{totalClients:0,activeClients:0,expiringLicenses:0,pendingPayments:0,revenueToday:0,revenueMonth:0}};
const paidStatuses=['Paid','Manually verified'];
const colors=['#4f8cff','#23d18b','#f8b84e','#a879ff','#ff647c','#37c8ff','#ff8d4d'];

export default function BusinessDashboard({section,canWrite}:{section:string;canWrite:boolean}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');
 const [selected,setSelected]=useState<Client|null>(null),[modal,setModal]=useState<{type:Resource;record?:RecordValue;client?:Client}|null>(null);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/business',{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.ok){setData(p);setError('')}else setError(p.error||'Unable to load business data');setLoading(false)},[]);
 useEffect(()=>{load()},[load]); useEffect(()=>{setSearch('');setFilter('All')},[section]);
 const clientName=useCallback((id:string)=>data.clients.find(c=>c.id===id)?.full_name||'Unknown client',[data.clients]);
 const remove=async(type:Resource,record:RecordValue)=>{if(!confirm(`Delete this ${type}? This action cannot be undone.${type==='client'?' Linked licenses, payments and activity will also be deleted.':''}`))return;const r=await fetch('/api/business',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:type,id:record.id})});const p=await r.json().catch(()=>({}));if(!r.ok){alert(p.error||'Unable to delete record');return}setSelected(null);await load()};
 const inviteClient=async(client:Client)=>{if(!client.email){alert('Add a valid client email before sending an invitation.');return}if(!confirm(`Send a secure Orion portal invitation to ${client.email}?`))return;const r=await fetch('/api/client-onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:client.id})});const p=await r.json().catch(()=>({}));if(!r.ok){alert(p.error||'Unable to send invitation');return}alert(`Invitation sent to ${p.email}. The client can now set a password and access the portal.`);setSelected(null);await load()};
 const q=search.toLowerCase().trim();
 const clients=useMemo(()=>data.clients.filter(c=>(filter==='All'||c.status===filter||c.plan===filter)&&`${c.full_name} ${c.email||''} ${c.telegram_username||''} ${c.country||''} ${c.plan} ${c.status}`.toLowerCase().includes(q)),[data.clients,q,filter]);
 const licenses=useMemo(()=>data.licenses.filter(x=>{const status=licenseStatus(x);return(filter==='All'||status===filter||x.platform===filter||x.plan===filter)&&`${x.license_key} ${x.account_number||''} ${x.platform} ${x.plan} ${status} ${clientName(x.client_id)}`.toLowerCase().includes(q)}),[data.licenses,clientName,q,filter]);
 const payments=useMemo(()=>data.payments.filter(x=>(filter==='All'||x.status===filter||x.method===filter||x.plan===filter)&&`${x.reference_id||''} ${x.method} ${x.plan} ${x.status} ${x.currency} ${x.amount} ${data.licenses.find(l=>l.id===x.license_id)?.license_key||''} ${clientName(x.client_id)}`.toLowerCase().includes(q)),[data.payments,data.licenses,clientName,q,filter]);
 if(loading)return <div className="business-loading"><span/>Loading secure client records…</div>;
 if(error)return <article className="panel migration-notice"><p className="eyebrow">Database setup required</p><h2>Apply the Phase 3 migration</h2><p className="muted">{error}</p><code>supabase/migrations/20260716_orion_business.sql</code></article>;
 return <>
  {section==='sales'&&<><Toolbar title="Sales reports" subtitle="Revenue and client performance across the Orion business." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Basic','Premium','Lifetime','Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} exportType="payments"/><SalesV2 data={{...data,payments}} search={q}/></>}
  {section==='clients'&&<><Toolbar title="Client management" subtitle="Customer profiles, plans, payments and activity." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Active','Expired','Suspended','Basic','Premium','Lifetime']} action="Add client" onAction={canWrite?()=>setModal({type:'client'}):undefined} exportType="clients"/><ClientSummary rows={data.clients}/><div className="client-grid">{clients.map(c=><ClientCard key={c.id} client={c} licenses={data.licenses.filter(x=>x.client_id===c.id)} payments={data.payments.filter(x=>x.client_id===c.id)} open={()=>setSelected(c)} edit={canWrite?()=>setModal({type:'client',record:c}):undefined} remove={canWrite?()=>remove('client',c):undefined}/>)}{!clients.length&&<Empty text="No clients match this search or filter."/>}</div></>}
  {section==='licenses'&&<><Toolbar title="License manager" subtitle="Generate, search and manage Orion MT4/MT5 licenses." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Active','Expired','Suspended','MT4','MT5','Basic','Premium','Lifetime']} action="Generate license" onAction={canWrite&&data.clients.length?()=>setModal({type:'license'}):undefined} exportType="licenses"/><LicenseSummary rows={data.licenses}/><ExpiringLicenses rows={data.licenses} clientName={clientName}/><LicenseTable rows={licenses} clientName={clientName} edit={canWrite?(x)=>setModal({type:'license',record:x}):undefined} remove={canWrite?(x)=>remove('license',x):undefined}/></>}
  {section==='payments'&&<><Toolbar title="Manual payments" subtitle="Search, review and maintain linked transaction records." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Basic','Premium','Lifetime','Pending','Paid','Manually verified','Failed','Refunded','Disputed','Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} action="Record payment" onAction={canWrite&&data.clients.length?()=>setModal({type:'payment'}):undefined} exportType="payments"/><PaymentSummary rows={data.payments}/><PaymentTable rows={payments} clientName={clientName} licenseKey={id=>data.licenses.find(l=>l.id===id)?.license_key||'—'} edit={canWrite?(x)=>setModal({type:'payment',record:x}):undefined} remove={canWrite?(x)=>remove('payment',x):undefined}/></>}
  {section==='activity'&&<><Toolbar title="Client activity" subtitle="Chronological audit trail of business changes."/><ActivityList rows={data.activity} clientName={clientName}/></>}
  {selected&&!modal&&<ClientProfile client={selected} licenses={data.licenses.filter(x=>x.client_id===selected.id)} payments={data.payments.filter(x=>x.client_id===selected.id)} activity={data.activity.filter(x=>x.client_id===selected.id)} canWrite={canWrite} close={()=>setSelected(null)} edit={()=>setModal({type:'client',record:selected})} remove={()=>remove('client',selected)} invite={()=>inviteClient(selected)} addLicense={()=>setModal({type:'license',client:selected})} addPayment={()=>setModal({type:'payment',client:selected})} editRecord={(type,record)=>setModal({type,record})} removeRecord={remove}/>} {/* profile */}
  {modal&&<RecordModal {...modal} clients={data.clients} licenses={data.licenses} close={()=>setModal(null)} saved={async()=>{setModal(null);setSelected(null);await load()}}/>}
 </>;
}

function Sales({data,search}:{data:Data;search:string}){const paid=data.payments.filter(p=>paidStatuses.includes(p.status)&&`${p.reference_id||''} ${p.method} ${p.plan} ${p.currency} ${p.amount}`.toLowerCase().includes(search));const total=paid.reduce((s,p)=>s+Number(p.amount),0);const group=(labels:string[],value:(p:Payment)=>string)=>labels.map(name=>({name,value:paid.filter(p=>value(p)===name).reduce((s,p)=>s+Number(p.amount),0)})).filter(x=>x.value>0);const plans=['Basic','Premium','Lifetime'];const byPlan=plans.map(name=>({name,value:paid.filter(p=>p.plan===name).reduce((s,p)=>s+Number(p.amount),0)}));const countries=[...new Set(data.clients.map(c=>c.country||'Unknown'))];const byCountry=countries.map(name=>({name,value:paid.filter(p=>(data.clients.find(c=>c.id===p.client_id)?.country||'Unknown')===name).reduce((s,p)=>s+Number(p.amount),0)})).sort((a,b)=>b.value-a.value).slice(0,10);const clientsByCountry=countries.map(name=>({name,value:data.clients.filter(c=>(c.country||'Unknown')===name).length})).sort((a,b)=>b.value-a.value).slice(0,10);const methods=[...new Set(data.payments.map(p=>p.method))];const byMethod=group(methods,p=>p.method);return <><div className="business-kpis"><Metric label="All-time revenue" value={money(total)} note={`${paid.length} completed payments`} color="green"/><Metric label="Revenue this month" value={money(data.metrics.revenueMonth)} note="Paid + verified" color="gold"/><Metric label="Total clients" value={data.metrics.totalClients} note={`${data.metrics.activeClients} active`} color="blue"/><Metric label="Pending payments" value={data.metrics.pendingPayments} note="Needs review" color="orange"/></div><div className="report-grid"><Chart title="Revenue by plan" data={byPlan} type="bar"/><Chart title="Revenue by country" data={byCountry} type="bar"/><Chart title="Clients by country" data={clientsByCountry} type="bar"/><Chart title="Revenue by payment method" data={byMethod} type="pie"/></div><PaymentTable rows={paid.slice(0,12)} clientName={id=>data.clients.find(c=>c.id===id)?.full_name||'Client'} licenseKey={id=>data.licenses.find(l=>l.id===id)?.license_key||'—'} compact/></>}
function Chart({title,data,type}:{title:string;data:{name:string;value:number}[];type:'bar'|'pie'}){return <article className="panel report-card"><p className="eyebrow">Sales intelligence</p><h2>{title}</h2><div className="report-chart">{data.length?<ResponsiveContainer width="100%" height="100%">{type==='bar'?<BarChart data={data} margin={{top:15,right:8,left:0,bottom:12}}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="name" stroke="#777" tick={{fontSize:11}}/><YAxis stroke="#777" tick={{fontSize:11}}/><Tooltip contentStyle={{background:'#080808',border:'1px solid rgba(255,255,255,.12)',borderRadius:12}}/><Bar dataKey="value" radius={[7,7,0,0]}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart>:<PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={52} outerRadius={85} paddingAngle={3}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'#080808',border:'1px solid rgba(255,255,255,.12)',borderRadius:12}}/></PieChart>}</ResponsiveContainer>:<Empty text="No paid records for this report."/>}</div><div className="chart-legend">{data.slice(0,7).map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{type==='pie'?money(x.value):x.value.toLocaleString()}</b></span>)}</div></article>}
function ClientSummary({rows}:{rows:Client[]}){const count=(field:'status'|'plan',value:string)=>rows.filter(row=>row[field]===value).length;return <div className="business-kpis summary-kpis"><Metric label="Total clients" value={rows.length} note="All client records" color="blue"/><Metric label="Active clients" value={count('status','Active')} note="Currently active" color="green"/><Metric label="Inactive clients" value={rows.length-count('status','Active')} note="Expired or suspended" color="orange"/><Metric label="Basic clients" value={count('plan','Basic')} note="Basic plan" color="blue"/><Metric label="Premium clients" value={count('plan','Premium')} note="Premium plan" color="purple"/><Metric label="Lifetime clients" value={count('plan','Lifetime')} note="Lifetime plan" color="gold"/></div>}
function LicenseSummary({rows}:{rows:License[]}){const plan=(value:string)=>rows.filter(row=>row.plan===value).length;const active=rows.filter(row=>licenseStatus(row)==='Active').length;const accounts=new Set(rows.map(row=>row.account_number?.trim()).filter(Boolean)).size;const soon=expiringSoon(rows);return <div className="business-kpis summary-kpis"><Metric label="Total licenses" value={rows.length} note="All generated keys" color="blue"/><Metric label="Active licenses" value={active} note="Ready for use" color="green"/><Metric label="Inactive licenses" value={rows.length-active} note="Expired or suspended" color="orange"/><Metric label="Basic licenses" value={plan('Basic')} note="Basic plan" color="blue"/><Metric label="Premium licenses" value={plan('Premium')} note="Premium plan" color="purple"/><Metric label="Lifetime licenses" value={plan('Lifetime')} note="Lifetime plan" color="gold"/><Metric label="Total accounts" value={accounts} note="Unique account numbers" color="green"/><Metric label="Expiring soon" value={soon.length} note="Within 30 days" color="orange"/></div>}
function licenseStatus(row:License){if(row.expires_at){const end=new Date(`${row.expires_at.slice(0,10)}T23:59:59.999Z`).getTime();if(!Number.isNaN(end)&&end<Date.now())return 'Expired'}return row.status}
function expiringSoon(rows:License[]){const now=Date.now(),limit=now+30*86400000;const end=(date:string)=>new Date(`${date.slice(0,10)}T23:59:59.999Z`).getTime();return rows.filter(row=>licenseStatus(row)==='Active'&&row.expires_at&&end(row.expires_at)>=now&&end(row.expires_at)<=limit).sort((a,b)=>end(a.expires_at!)-end(b.expires_at!))}
function ExpiringLicenses({rows,clientName}:{rows:License[];clientName:(id:string)=>string}){const soon=expiringSoon(rows);if(!soon.length)return null;return <article className="panel expiry-panel"><div><p className="eyebrow">Renewal attention</p><h2>Licenses expiring soon</h2></div><div className="expiry-list">{soon.slice(0,8).map(row=>{const days=Math.max(0,Math.ceil((new Date(row.expires_at!).getTime()-Date.now())/86400000));return <span key={row.id}><strong>{clientName(row.client_id)}</strong><code>{row.license_key}</code><b>{days} day{days===1?'':'s'} left</b></span>})}</div></article>}
function PaymentSummary({rows}:{rows:Payment[]}){const methods=['Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other'];return <div className="business-kpis summary-kpis payment-summary"><Metric label="Total payments" value={rows.length} note={`${rows.filter(row=>paidStatuses.includes(row.status)).length} completed`} color="blue"/>{methods.map((method,index)=>{const methodRows=rows.filter(row=>row.method===method);const paid=methodRows.filter(row=>paidStatuses.includes(row.status)).reduce((sum,row)=>sum+Number(row.amount),0);return <Metric key={method} label={method} value={methodRows.length} note={`${money(paid)} received`} color={['green','gold','purple','blue','orange'][index%5]}/>})}</div>}
function SalesV2({data,search}:{data:Data;search:string}){const paid=data.payments.filter(row=>paidStatuses.includes(row.status)&&`${row.reference_id||''} ${row.method} ${row.plan} ${row.currency} ${row.amount}`.toLowerCase().includes(search));const planTotal=(plan:string)=>paid.filter(row=>row.plan===plan).reduce((sum,row)=>sum+Number(row.amount),0);const total=paid.reduce((sum,row)=>sum+Number(row.amount),0);const methods=[...new Set(paid.map(row=>row.method))];const byMethod=methods.map(name=>({name,value:paid.filter(row=>row.method===name).reduce((sum,row)=>sum+Number(row.amount),0)}));const countries=[...new Set(data.clients.map(row=>row.country||'Unknown'))];const byCountry=countries.map(name=>({name,value:paid.filter(row=>(data.clients.find(client=>client.id===row.client_id)?.country||'Unknown')===name).reduce((sum,row)=>sum+Number(row.amount),0)})).filter(row=>row.value>0).sort((a,b)=>b.value-a.value).slice(0,10);return <><div className="business-kpis sales-kpis"><Metric label="All-time revenue" value={money(total)} note="Completed sales" color="green"/><Metric label="Total payments" value={data.payments.length} note={`${paid.length} completed`} color="blue"/><Metric label="Basic plan revenue" value={money(planTotal('Basic'))} note="Historical Basic sales" color="blue"/><Metric label="Premium plan revenue" value={money(planTotal('Premium'))} note="Historical Premium sales" color="purple"/><Metric label="Lifetime plan revenue" value={money(planTotal('Lifetime'))} note="Historical Lifetime sales" color="gold"/></div><div className="report-grid varied-reports"><TrendCard title="Daily revenue this month" subtitle="Revenue for every day of the current month" data={currentMonthDaily(paid)} kind="area" color="#23d18b"/><TrendCard title="Balance trend" subtitle="Cumulative completed revenue" data={balanceTrend(paid)} kind="line" color="#a879ff"/><Chart title="Revenue by payment method" data={byMethod} type="pie"/><HorizontalBars title="Revenue by country" data={byCountry}/></div><PaymentTable rows={paid.slice(0,12)} clientName={id=>data.clients.find(client=>client.id===id)?.full_name||'Client'} licenseKey={id=>data.licenses.find(license=>license.id===id)?.license_key||'—'} compact/></>}
function currentMonthDaily(rows:Payment[]){const now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return Array.from({length:days},(_,index)=>{const day=index+1,date=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return{name:String(day),value:rows.filter(row=>row.payment_date===date).reduce((sum,row)=>sum+Number(row.amount),0)}})}
function balanceTrend(rows:Payment[]){let balance=0;const grouped=new Map<string,number>();rows.filter(row=>row.payment_date).sort((a,b)=>a.payment_date!.localeCompare(b.payment_date!)).forEach(row=>grouped.set(row.payment_date!,Number(grouped.get(row.payment_date!)||0)+Number(row.amount)));return [...grouped].map(([date,value])=>({name:new Date(`${date}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}),value:balance+=value})).slice(-45)}
function TrendCard({title,subtitle,data,kind,color}:{title:string;subtitle:string;data:{name:string;value:number}[];kind:'area'|'line';color:string}){return <article className="panel report-card trend-card"><p className="eyebrow">Revenue trend</p><h2>{title}</h2><small>{subtitle}</small><div className="report-chart"><ResponsiveContainer width="100%" height="100%">{kind==='area'?<AreaChart data={data}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity={.38}/><stop offset="1" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.05)" vertical={false}/><XAxis dataKey="name" stroke="#666" tick={{fontSize:10}}/><YAxis stroke="#666" tick={{fontSize:10}}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="value" stroke={color} strokeWidth={3} fill="url(#revenueFill)"/></AreaChart>:<LineChart data={data}><CartesianGrid stroke="rgba(255,255,255,.05)" vertical={false}/><XAxis dataKey="name" stroke="#666" tick={{fontSize:10}}/><YAxis stroke="#666" tick={{fontSize:10}}/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="value" stroke={color} strokeWidth={3} dot={false} activeDot={{r:5,fill:color}}/></LineChart>}</ResponsiveContainer></div></article>}
function HorizontalBars({title,data}:{title:string;data:{name:string;value:number}[]}){return <article className="panel report-card"><p className="eyebrow">Market performance</p><h2>{title}</h2><div className="report-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:15,right:20}}><CartesianGrid stroke="rgba(255,255,255,.05)" horizontal={false}/><XAxis type="number" stroke="#666" tick={{fontSize:10}}/><YAxis type="category" dataKey="name" width={108} stroke="#777" tick={{fontSize:10}} tickFormatter={countryLabel}/><Tooltip contentStyle={tooltipStyle} labelFormatter={countryLabel}/><Bar dataKey="value" radius={[0,8,8,0]}>{data.map((_,index)=><Cell key={index} fill={colors[index%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></article>}
const tooltipStyle={background:'#080808',border:'1px solid rgba(255,255,255,.12)',borderRadius:12};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function metricIcon(label:string){const value=label.toLowerCase();if(value.includes('revenue')||value.includes('balance'))return '↗';if(value.includes('payment'))return '◈';if(value.includes('client'))return '♙';if(value.includes('license'))return '◇';if(value.includes('account'))return '◎';if(value.includes('expir')||value.includes('inactive'))return '◷';if(value.includes('active'))return '●';if(value.includes('premium'))return '✦';if(value.includes('lifetime'))return '∞';if(value.includes('basic'))return '◆';return '✧'}
function Metric({label,value,note,color}:{label:string;value:string|number;note:string;color:string}){return <article className={`metric-card biz-metric ${color}`}><span className="metric-icon" aria-hidden="true">{metricIcon(label)}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Toolbar({title,subtitle,search,setSearch,filter,setFilter,options=[],action,onAction,exportType}:{title:string;subtitle:string;search?:string;setSearch?:(v:string)=>void;filter?:string;setFilter?:(v:string)=>void;options?:string[];action?:string;onAction?:()=>void;exportType?:string}){return <div className="business-toolbar"><div><p className="eyebrow">Orion operations</p><h2>{title}</h2><p className="muted">{subtitle}</p></div><div className="business-actions">{setSearch&&<input aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/>} {setFilter&&<select aria-label={`Filter ${title}`} value={filter} onChange={e=>setFilter(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}{exportType&&<a className="glass-button" href={`/api/business/export?type=${exportType}`}>Export CSV</a>}{onAction&&<button className="gold-button" onClick={onAction}>＋ {action}</button>}</div></div>}
function RowActions({edit,remove}:{edit?:()=>void;remove?:()=>void}){return edit||remove?<span className="row-actions">{edit&&<button onClick={edit} aria-label="Edit record">Edit</button>}{remove&&<button className="danger" onClick={remove} aria-label="Delete record">Delete</button>}</span>:null}
function ClientCard({client,licenses,payments,open,edit,remove}:{client:Client;licenses:License[];payments:Payment[];open:()=>void;edit?:()=>void;remove?:()=>void}){const paid=payments.filter(p=>paidStatuses.includes(p.status)).reduce((s,p)=>s+Number(p.amount),0);return <article className="panel client-card"><button className="client-card-main" onClick={open}><div className="client-card-top"><span className="client-avatar">{client.full_name.split(' ').map(p=>p[0]).slice(0,2).join('').toUpperCase()}</span><Status value={client.status}/></div><h3>{client.full_name}</h3><p>{client.email||client.telegram_username||'No contact added'}</p><p className="client-country">{countryFlag(client.country)} {client.country||'Country not set'}</p><div className="client-card-meta"><span><small>Plan</small>{client.plan}</span><span><small>Licenses</small>{licenses.length}</span><span><small>Portal</small><b className={client.auth_user_id?'portal-linked':'portal-unlinked'}>{client.auth_user_id?'Linked':'Not linked'}</b></span></div></button><RowActions edit={edit} remove={remove}/></article>}
function LicenseTable({rows,clientName,edit,remove}:{rows:License[];clientName:(id:string)=>string;edit?:(r:License)=>void;remove?:(r:License)=>void}){return <article className="panel table-panel full business-table"><div className="data-table"><div className="table-head license-head"><span>Client</span><span>License</span><span>Platform</span><span>Account</span><span>Expiry</span><span>Status</span><span>Actions</span></div>{rows.map(r=><div className="table-row license-row" key={r.id}><strong>{clientName(r.client_id)}</strong><code>{r.license_key}</code><span>{r.platform}</span><span>{r.account_number||'—'}</span><time>{r.expires_at?new Date(`${r.expires_at.slice(0,10)}T00:00:00`).toLocaleDateString():'Lifetime'}</time><Status value={licenseStatus(r)}/><RowActions edit={edit?()=>edit(r):undefined} remove={remove?()=>remove(r):undefined}/></div>)}{!rows.length&&<Empty text="No licenses match this search or filter."/>}</div></article>}
function PaymentTable({rows,clientName,licenseKey=()=> '—',edit,remove,compact=false}:{rows:Payment[];clientName:(id:string)=>string;licenseKey?:(id?:string)=>string;edit?:(r:Payment)=>void;remove?:(r:Payment)=>void;compact?:boolean}){return <article className={`panel table-panel full business-table ${compact?'compact':''}`}><div className="data-table"><div className="table-head payment-head"><span>Client</span><span>Plan</span><span>License</span><span>Method</span><span>Amount</span><span>Date</span><span>Reference</span><span>Status</span><span>Actions</span></div>{rows.map(r=><div className="table-row payment-row" key={r.id}><strong>{clientName(r.client_id)}</strong><span>{r.plan||'—'}</span><code>{licenseKey(r.license_id)}</code><span>{r.method}</span><span>{r.currency} {Number(r.amount).toLocaleString()}</span><time>{r.payment_date?new Date(`${r.payment_date}T00:00:00`).toLocaleDateString():'—'}</time><code>{r.reference_id||'—'}</code><Status value={r.status}/><RowActions edit={edit?()=>edit(r):undefined} remove={remove?()=>remove(r):undefined}/></div>)}{!rows.length&&<Empty text="No payments match this search or filter."/>}</div></article>}
function ActivityList({rows,clientName,embedded=false}:{rows:Activity[];clientName:(id:string)=>string;embedded?:boolean}){const body=<div className="activity-list">{rows.map(r=><div className="activity-item" key={r.id}><i/><div><strong>{r.action}</strong><span>{clientName(r.client_id)} · {r.details||'Record updated'}</span><small>{new Date(r.created_at).toLocaleString()} {r.actor_email?`· ${r.actor_email}`:''}</small></div></div>)}{!rows.length&&<Empty text="No activity recorded yet."/>}</div>;return embedded?body:<article className="panel activity-panel">{body}</article>}
function Status({value}:{value:string}){return <span className={`record-status ${value.toLowerCase().replace(/\s/g,'-')}`}>{value}</span>}
function Empty({text}:{text:string}){return <p className="empty-state business-empty">{text}</p>}

function ClientProfile({client,licenses,payments,activity,canWrite,close,edit,remove,invite,addLicense,addPayment,editRecord,removeRecord}:{client:Client;licenses:License[];payments:Payment[];activity:Activity[];canWrite:boolean;close:()=>void;edit:()=>void;remove:()=>void;invite:()=>void;addLicense:()=>void;addPayment:()=>void;editRecord:(t:Resource,r:RecordValue)=>void;removeRecord:(t:Resource,r:RecordValue)=>void}){return <div className="modal-backdrop" onMouseDown={close}><section className="profile-drawer" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><div className="profile-hero"><span className="client-avatar large">{client.full_name.slice(0,2).toUpperCase()}</span><div><p className="eyebrow">Client profile</p><h2>{client.full_name}</h2><p>{client.email||'No email'} · {client.country||'Country not set'}</p></div><Status value={client.status}/></div><div className="profile-facts"><span><small>Plan</small>{client.plan}</span><span><small>Portal access</small><b className={client.auth_user_id?'portal-linked':'portal-unlinked'}>{client.auth_user_id?'Linked':'Not linked'}</b></span><span><small>Phone</small>{client.phone||'—'}</span><span><small>Joined</small>{new Date(client.created_at).toLocaleDateString()}</span></div>{canWrite&&<div className="profile-actions"><button className="glass-button" onClick={edit}>Edit client</button>{!client.auth_user_id&&<button className="invite-button" onClick={invite}>✉ Invite to portal</button>}<button className="gold-button" onClick={addLicense}>＋ License</button><button className="glass-button" onClick={addPayment}>＋ Payment</button><button className="danger-button" onClick={remove}>Delete client</button></div>}<h3>Licenses</h3><LicenseTable rows={licenses} clientName={()=>client.full_name} edit={canWrite?r=>editRecord('license',r):undefined} remove={canWrite?r=>removeRecord('license',r):undefined}/><h3>Payments</h3><PaymentTable rows={payments} clientName={()=>client.full_name} edit={canWrite?r=>editRecord('payment',r):undefined} remove={canWrite?r=>removeRecord('payment',r):undefined}/><h3>Activity timeline</h3><ActivityList rows={activity} clientName={()=>client.full_name} embedded/>{client.notes&&<div className="profile-notes"><small>Internal notes</small><p>{client.notes}</p></div>}</section></div>}

function RecordModal({type,record,client,clients,licenses,close,saved}:{type:Resource;record?:RecordValue;client?:Client;clients:Client[];licenses:License[];close:()=>void;saved:()=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState('');const editing=Boolean(record);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const data=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch('/api/business',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resource:type,id:record?.id,data})});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p.error||'Unable to save');setSaving(false);return}await saved()}return <div className="modal-backdrop" onMouseDown={close}><form className="record-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">{editing?'Edit':'New'} {type}</p><h2>{editing?'Update record':type==='client'?'Add a client':type==='license'?'Generate a license':'Record a payment'}</h2>{type==='client'?<ClientFields value={record as Client}/>:type==='license'?<LicenseFields clients={clients} selected={client} value={record as License}/>:<PaymentFields clients={clients} licenses={licenses} selected={client} value={record as Payment}/>} {error&&<p className="form-error">{error}</p>}<button className="gold-button modal-submit" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Save record'}</button></form></div>}
function ClientFields({value}:{value?:Client}){return <div className="form-grid"><Field label="Full name" name="full_name" required value={value?.full_name}/><Field label="Email" name="email" type="email" value={value?.email}/><Field label="Telegram username" name="telegram_username" value={value?.telegram_username}/><Field label="Phone" name="phone" value={value?.phone}/><Field label="Country" name="country" value={value?.country}/><Select label="Plan" name="plan" options={['Basic','Premium','Lifetime']} value={value?.plan}/><Select label="Status" name="status" options={['Active','Expired','Suspended']} value={value?.status}/><label className="wide"><span>Supabase Auth user UUID</span><input name="auth_user_id" defaultValue={value?.auth_user_id}/><small>Link the Authentication → Users UUID to enable this client’s portal.</small></label><label className="wide"><span>Notes</span><textarea name="notes" rows={4} defaultValue={value?.notes}/></label></div>}
function LicenseFields({clients,selected,value}:{clients:Client[];selected?:Client;value?:License}){return <div className="form-grid"><ClientSelect clients={clients} selectedId={value?.client_id||selected?.id}/><Field label="License key" name="license_key" value={value?.license_key||`ORN-${crypto.randomUUID().slice(0,8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`} required/><Select label="Platform" name="platform" options={['MT5','MT4']} value={value?.platform}/><Field label="Account number" name="account_number" value={value?.account_number}/><Select label="Plan" name="plan" options={['Basic','Premium','Lifetime']} value={value?.plan}/><Select label="Status" name="status" options={['Active','Expired','Suspended']} value={value?.status}/><Field label="Expiry date" name="expires_at" type="date" value={value?.expires_at?.slice(0,10)}/></div>}
function PaymentFields({clients,licenses,selected,value}:{clients:Client[];licenses:License[];selected?:Client;value?:Payment}){const [clientId,setClientId]=useState(value?.client_id||selected?.id||clients[0]?.id||'');const [licenseId,setLicenseId]=useState(value?.license_id||'');const [plan,setPlan]=useState(value?.plan||clients.find(c=>c.id===clientId)?.plan||'Basic');const eligible=licenses.filter(l=>l.client_id===clientId);function chooseLicense(id:string){setLicenseId(id);const license=licenses.find(l=>l.id===id);if(license)setPlan(license.plan)}return <div className="form-grid"><ClientSelect clients={clients} selectedId={clientId} onChange={id=>{setClientId(id);setLicenseId('');setPlan(clients.find(c=>c.id===id)?.plan||'Basic')}}/><label><span>Purchased plan</span><select name="plan" value={plan} onChange={e=>setPlan(e.target.value)}>{['Basic','Premium','Lifetime'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Related license (optional)</span><select name="license_id" value={licenseId} onChange={e=>chooseLicense(e.target.value)}><option value="">No linked license</option>{eligible.map(l=><option key={l.id} value={l.id}>{l.license_key} · {l.platform} · {l.plan}</option>)}</select></label><Select label="Payment method" name="method" options={['Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} value={value?.method}/><Select label="Payment status" name="status" options={['Pending','Paid','Manually verified','Failed','Refunded','Disputed']} value={value?.status}/><Field label="Amount" name="amount" type="number" value={String(value?.amount??0)} required/><Field label="Currency" name="currency" value={value?.currency||'USD'} required/><Field label="Payment date" name="payment_date" type="date" value={value?.payment_date?.slice(0,10)}/><Field label="Transaction / reference ID" name="reference_id" value={value?.reference_id}/><label className="wide"><span>Notes</span><textarea name="notes" rows={3} defaultValue={value?.notes}/></label></div>}
function ClientSelect({clients,selectedId,onChange}:{clients:Client[];selectedId?:string;onChange?:(id:string)=>void}){return <label className="wide"><span>Client</span><select name="client_id" value={onChange?selectedId:undefined} defaultValue={onChange?undefined:selectedId} onChange={e=>onChange?.(e.target.value)} required>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label>}
function Field({label,name,type='text',required=false,value}:{label:string;name:string;type?:string;required?:boolean;value?:string}){return <label><span>{label}</span><input name={name} type={type} required={required} defaultValue={value} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined}/></label>}
function Select({label,name,options,value}:{label:string;name:string;options:string[];value?:string}){return <label><span>{label}</span><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
