'use client';

import { FormEvent, KeyboardEvent, useCallback, useEffect, useMemo, useRef, useState, type RefObject } from 'react';
import { countryFlag } from '@/lib/country';
import Client360Panel from '@/components/client-360-panel';
import RevenueIntelligence from '@/components/revenue-intelligence';
import SalesCommandCenter from '@/components/sales-command-center';

type Client = { id:string; auth_user_id?:string; full_name:string; email?:string; telegram_username?:string; phone?:string; country?:string; plan:string; status:string; notes?:string; reviewed_at?:string; reviewed_by?:string; created_at:string };
type License = { id:string; client_id:string; license_key:string; platform:string; account_number?:string; plan:string; status:string; issued_at:string; expires_at?:string };
type Payment = { id:string; client_id:string; license_id?:string; receipt_number?:string; receipt_sent_at?:string; plan:string; method:string; status:string; amount:number; currency:string; payment_date?:string; reference_id?:string; notes?:string; created_at:string; updated_at?:string };
type Activity = { id:string; client_id:string; action:string; details?:string; actor_email?:string; created_at:string };
type Resource = 'client'|'license'|'payment';
type RecordValue = Client|License|Payment;
type Data = { clients:Client[]; licenses:License[]; payments:Payment[]; activity:Activity[]; metrics:{ totalClients:number; activeClients:number; expiringLicenses:number; pendingPayments:number; revenueToday:number; revenueMonth:number } };
type BusinessDashboardProps = { section:string; canWrite:boolean; initialFilter?:string; initialSearch?:string; navigationKey?:number; commandAction?:{type:'add-client'|'create-license'|'record-payment';key:number} };
const empty:Data={clients:[],licenses:[],payments:[],activity:[],metrics:{totalClients:0,activeClients:0,expiringLicenses:0,pendingPayments:0,revenueToday:0,revenueMonth:0}};
const paidStatuses=['Paid','Manually verified'];

function handleDialogKeyDown(event:KeyboardEvent<HTMLElement>,close:()=>void){if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab')return;const focusable=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}

export default function BusinessDashboard({section,canWrite,initialFilter,initialSearch,navigationKey=0,commandAction}:BusinessDashboardProps){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');
 const [selected,setSelected]=useState<Client|null>(null),[modal,setModal]=useState<{type:Resource;record?:RecordValue;client?:Client}|null>(null);
 const toolbarHeadingRef=useRef<HTMLHeadingElement>(null),focusedNavigationKey=useRef<number|null>(null);
 const queuedFilter=initialFilter?.trim()||'',queuedSearch=initialSearch?.trim()||'',handledCommandKey=useRef<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/business',{cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Unable to load business data');setData(p);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load business data')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]); useEffect(()=>{setSearch(queuedSearch);setFilter(queuedFilter||'All')},[section,queuedFilter,queuedSearch,navigationKey]);
 useEffect(()=>{if(loading||!canWrite||!commandAction||handledCommandKey.current===commandAction.key)return;handledCommandKey.current=commandAction.key;if(commandAction.type==='add-client')setModal({type:'client'});else if(commandAction.type==='create-license'&&data.clients.length)setModal({type:'license'});else if(commandAction.type==='record-payment'&&data.clients.length)setModal({type:'payment'})},[canWrite,commandAction,data.clients.length,loading]);
 const clientName=useCallback((id:string)=>data.clients.find(c=>c.id===id)?.full_name||'Unknown client',[data.clients]);
 const remove=async(type:Resource,record:RecordValue)=>{if(!confirm(`Delete this ${type}? This action cannot be undone.${type==='client'?' Linked licenses, payments and activity will also be deleted.':''}`))return;const r=await fetch('/api/business',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:type,id:record.id})});const p=await r.json().catch(()=>({}));if(!r.ok){alert(p.error||'Unable to delete record');return}setSelected(null);await load()};
 const inviteClient=async(client:Client)=>{if(!client.email){alert('Add a valid client email before sending an invitation.');return}if(!confirm(`Send a secure Orion portal invitation to ${client.email}?`))return;const r=await fetch('/api/client-onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:client.id})});const p=await r.json().catch(()=>({}));if(!r.ok){alert(p.error||'Unable to send invitation');return}alert(`Invitation sent to ${p.email}. The client can now set a password and access the portal.`);setSelected(null);await load()};
 const q=search.toLowerCase().trim();
 const clients=useMemo(()=>data.clients.filter(c=>(filter==='All'||c.status===filter||c.plan===filter)&&`${c.full_name} ${c.email||''} ${c.telegram_username||''} ${c.country||''} ${c.plan} ${c.status}`.toLowerCase().includes(q)),[data.clients,q,filter]);
 const licenses=useMemo(()=>{const now=Date.now();return data.licenses.filter(x=>{const status=licenseStatus(x,now),matchesFilter=filter==='All'||(filter==='Expiring soon'&&isLicenseExpiringSoon(x,now))||status===filter||x.platform===filter||x.plan===filter;return matchesFilter&&`${x.license_key} ${x.account_number||''} ${x.platform} ${x.plan} ${status} ${clientName(x.client_id)}`.toLowerCase().includes(q)})},[data.licenses,clientName,q,filter]);
 const payments=useMemo(()=>data.payments.filter(x=>(filter==='All'||x.status===filter||x.method===filter||x.plan===filter)&&`${x.reference_id||''} ${x.method} ${x.plan} ${x.status} ${x.currency} ${x.amount} ${data.licenses.find(l=>l.id===x.license_id)?.license_key||''} ${clientName(x.client_id)}`.toLowerCase().includes(q)),[data.payments,data.licenses,clientName,q,filter]);
 const registrationResultCount=useMemo(()=>{const now=Date.now();return data.clients.filter(client=>registrationMatches(client,data.licenses,q,filter,now)).length},[data.clients,data.licenses,q,filter]);
 const visibleResultCount=section==='registrations'?registrationResultCount:section==='licenses'?licenses.length:section==='payments'||section==='sales'?payments.length:section==='clients'?clients.length:data.activity.length;
 const navigationAnnouncement=queuedFilter?`${filter} filter active. ${visibleResultCount} ${visibleResultCount===1?'result':'results'} shown.`:undefined;
 useEffect(()=>{if(loading||!queuedFilter||filter!==queuedFilter||focusedNavigationKey.current===navigationKey)return;toolbarHeadingRef.current?.focus();focusedNavigationKey.current=navigationKey},[filter,loading,navigationKey,queuedFilter,section]);
 if(loading)return <div className="business-loading"><span/>Loading secure client records…</div>;
 if(error)return <article className="panel migration-notice"><p className="eyebrow">Secure records unavailable</p><h2>Business data could not load</h2><p className="muted">{error}</p><p className="muted">If this is the first release of the new command suite, apply the migration below before retrying.</p><code>supabase/migrations/20260724_orion_command_suite.sql</code><button className="glass-button" type="button" onClick={()=>void load()}>Retry secure records</button></article>;
 return <>
  {section==='sales'&&<><Toolbar title="Sales performance" subtitle="Search or filter the command center below. Currency views stay separate for accurate reporting." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Basic','Premium','Lifetime','Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} exportType="payments" headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><SalesCommandCenter clients={data.clients} licenses={data.licenses} payments={payments} search={q}/><RevenueIntelligence/></>}
  {section==='registrations'&&<><Toolbar title="Registration queue" subtitle="Review new free accounts, pending clients and accounts without licenses." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Needs review','New this week','Free','Pending','Without license']} exportType="clients" headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><RegistrationQueue clients={data.clients} licenses={data.licenses} search={q} filter={filter} open={setSelected}/></>}
  {section==='clients'&&<><Toolbar title="Client management" subtitle="Customer profiles, plans, approvals, payments and activity." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Pending','Active','Expired','Suspended','Free','Basic','Premium','Lifetime']} action="Add client" onAction={canWrite?()=>setModal({type:'client'}):undefined} exportType="clients" headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><ClientSummary rows={data.clients}/><div className="client-grid">{clients.map(c=><ClientCard key={c.id} client={c} licenses={data.licenses.filter(x=>x.client_id===c.id)} payments={data.payments.filter(x=>x.client_id===c.id)} open={()=>setSelected(c)} edit={canWrite?()=>setModal({type:'client',record:c}):undefined} remove={canWrite?()=>remove('client',c):undefined}/>)}{!clients.length&&<Empty text="No clients match this search or filter."/>}</div></>}
  {section==='licenses'&&<><Toolbar title="License manager" subtitle="Generate, search and manage Orion MT4/MT5 licenses." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Active','Expiring soon','Expired','Suspended','MT4','MT5','Basic','Premium','Lifetime']} action="Generate license" onAction={canWrite&&data.clients.length?()=>setModal({type:'license'}):undefined} exportType="licenses" headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><LicenseSummary rows={data.licenses}/><ExpiringLicenses rows={data.licenses} clientName={clientName}/><LicenseTable rows={licenses} clientName={clientName} edit={canWrite?(x)=>setModal({type:'license',record:x}):undefined} remove={canWrite?(x)=>remove('license',x):undefined}/></>}
  {section==='payments'&&<><Toolbar title="Manual payments" subtitle="Search, review and maintain linked transaction records." search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} options={['All','Basic','Premium','Lifetime','Pending','Paid','Manually verified','Failed','Refunded','Disputed','Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} action="Record payment" onAction={canWrite&&data.clients.length?()=>setModal({type:'payment'}):undefined} exportType="payments" headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><PaymentSummary rows={data.payments}/><PaymentTable rows={payments} clientName={clientName} licenseKey={id=>data.licenses.find(l=>l.id===id)?.license_key||'—'} edit={canWrite?(x)=>setModal({type:'payment',record:x}):undefined} remove={canWrite?(x)=>remove('payment',x):undefined}/></>}
  {section==='activity'&&<><Toolbar title="Client activity" subtitle="Chronological audit trail of business changes." headingRef={toolbarHeadingRef} announcement={navigationAnnouncement}/><ActivityList rows={data.activity} clientName={clientName}/></>}
  {selected&&!modal&&<ClientProfile client={selected} licenses={data.licenses.filter(x=>x.client_id===selected.id)} payments={data.payments.filter(x=>x.client_id===selected.id)} activity={data.activity.filter(x=>x.client_id===selected.id)} canWrite={canWrite} close={()=>setSelected(null)} edit={()=>setModal({type:'client',record:selected})} remove={()=>remove('client',selected)} invite={()=>inviteClient(selected)} addLicense={()=>setModal({type:'license',client:selected})} addPayment={()=>setModal({type:'payment',client:selected})} editRecord={(type,record)=>setModal({type,record})} removeRecord={remove}/>} {/* profile */}
  {modal&&<RecordModal {...modal} clients={data.clients} licenses={data.licenses} close={()=>setModal(null)} saved={async()=>{setModal(null);setSelected(null);await load()}}/>}
 </>;
}

function ClientSummary({rows}:{rows:Client[]}){const count=(field:'status'|'plan',value:string)=>rows.filter(row=>row[field]===value).length;return <div className="business-kpis summary-kpis"><Metric label="Total clients" value={rows.length} note="All client records" color="blue"/><Metric label="Active clients" value={count('status','Active')} note="Currently active" color="green"/><Metric label="Inactive clients" value={rows.length-count('status','Active')} note="Expired or suspended" color="orange"/><Metric label="Basic clients" value={count('plan','Basic')} note="Basic plan" color="blue"/><Metric label="Premium clients" value={count('plan','Premium')} note="Premium plan" color="purple"/><Metric label="Lifetime clients" value={count('plan','Lifetime')} note="Lifetime plan" color="gold"/></div>}
function registrationMatches(client:Client,licenses:License[],search:string,filter:string,now=Date.now()){const weekAgo=now-7*86400000,hasLicense=licenses.some(license=>license.client_id===client.id),needsReview=!client.reviewed_at&&(client.status==='Pending'||(client.plan==='Free'&&Boolean(client.auth_user_id)));const matchesSearch=`${client.full_name} ${client.email||''} ${client.country||''} ${client.plan} ${client.status}`.toLowerCase().includes(search);const matchesFilter=filter==='All'||(filter==='Needs review'&&needsReview)||(filter==='New this week'&&new Date(client.created_at).getTime()>=weekAgo)||(filter==='Free'&&client.plan==='Free')||(filter==='Pending'&&client.status==='Pending')||(filter==='Without license'&&!hasLicense);return matchesSearch&&matchesFilter}
function RegistrationQueue({clients,licenses,search,filter,open}:{clients:Client[];licenses:License[];search:string;filter:string;open:(client:Client)=>void}){const now=Date.now(),weekAgo=now-7*86400000;const hasLicense=(id:string)=>licenses.some(license=>license.client_id===id);const rows=clients.filter(client=>registrationMatches(client,licenses,search,filter,now)).sort((a,b)=>b.created_at.localeCompare(a.created_at));const newCount=clients.filter(client=>new Date(client.created_at).getTime()>=weekAgo).length;const freeCount=clients.filter(client=>client.plan==='Free').length;const pendingCount=clients.filter(client=>client.status==='Pending').length;const unlicensed=clients.filter(client=>!hasLicense(client.id)).length;return <><div className="business-kpis registration-kpis"><Metric label="New this week" value={newCount} note="Recent registrations" color="blue"/><Metric label="Free accounts" value={freeCount} note="Potential upgrades" color="purple"/><Metric label="Pending approval" value={pendingCount} note="Requires review" color="orange"/><Metric label="Without license" value={unlicensed} note="No active assignment" color="gold"/></div><article className="panel registration-panel"><div className="registration-head"><span>Client</span><span>Country</span><span>Plan</span><span>Portal</span><span>License</span><span>Registered</span><span>Action</span></div>{rows.map(client=><div className="registration-row" key={client.id}><span className="registration-client"><i>{client.full_name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}</i><b>{client.full_name}<small>{client.email||'No email'}</small></b></span><span>{countryFlag(client.country)} {client.country||'Not set'}</span><span><Status value={client.plan}/></span><span><b className={client.auth_user_id?'portal-linked':'portal-unlinked'}>{client.auth_user_id?'Linked':'Not linked'}</b></span><span>{hasLicense(client.id)?'Assigned':'Not assigned'}</span><time>{new Date(client.created_at).toLocaleDateString()}</time><button className="glass-button" onClick={()=>open(client)}>Review</button></div>)}{!rows.length&&<Empty text="No registrations match this search or filter."/>}</article></>}
function LicenseSummary({rows}:{rows:License[]}){const plan=(value:string)=>rows.filter(row=>row.plan===value).length;const active=rows.filter(row=>licenseStatus(row)==='Active').length;const accounts=new Set(rows.map(row=>row.account_number?.trim()).filter(Boolean)).size;const soon=expiringSoon(rows);return <div className="business-kpis summary-kpis"><Metric label="Total licenses" value={rows.length} note="All generated keys" color="blue"/><Metric label="Active licenses" value={active} note="Ready for use" color="green"/><Metric label="Inactive licenses" value={rows.length-active} note="Expired or suspended" color="orange"/><Metric label="Basic licenses" value={plan('Basic')} note="Basic plan" color="blue"/><Metric label="Premium licenses" value={plan('Premium')} note="Premium plan" color="purple"/><Metric label="Lifetime licenses" value={plan('Lifetime')} note="Lifetime plan" color="gold"/><Metric label="Total accounts" value={accounts} note="Unique account numbers" color="green"/><Metric label="Expiring soon" value={soon.length} note="Within 30 days" color="orange"/></div>}
const DAY_MS=86400000;
function dateOnlyParts(value?:string){const match=/^(\d{4})-(\d{2})-(\d{2})/.exec(value||'');if(!match)return null;const year=Number(match[1]),monthIndex=Number(match[2])-1,day=Number(match[3]),check=new Date(Date.UTC(year,monthIndex,day));return check.getUTCFullYear()===year&&check.getUTCMonth()===monthIndex&&check.getUTCDate()===day?{year,monthIndex,day}:null}
function licenseExpiryTimestamp(value?:string,endOfDay=true){const parts=dateOnlyParts(value);return parts?Date.UTC(parts.year,parts.monthIndex,parts.day)+(endOfDay?DAY_MS-1:0):null}
function expiringSoonCutoff(now:number){const today=new Date(now);return Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate())+31*DAY_MS-1}
function licenseStatus(row:License,now=Date.now()){const end=licenseExpiryTimestamp(row.expires_at);return end!==null&&end<now?'Expired':row.status}
function isLicenseExpiringSoon(row:License,now=Date.now()){const end=licenseExpiryTimestamp(row.expires_at);return end!==null&&end>=now&&end<=expiringSoonCutoff(now)&&licenseStatus(row,now)==='Active'}
function expiringSoon(rows:License[],now=Date.now()){return rows.filter(row=>isLicenseExpiringSoon(row,now)).sort((a,b)=>(licenseExpiryTimestamp(a.expires_at)||Infinity)-(licenseExpiryTimestamp(b.expires_at)||Infinity))}
function daysUntilExpiry(value:string|undefined,now:number){const parts=dateOnlyParts(value),today=new Date(now);if(!parts)return 0;return Math.max(0,Math.round((Date.UTC(parts.year,parts.monthIndex,parts.day)-Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()))/DAY_MS))}
function ExpiringLicenses({rows,clientName}:{rows:License[];clientName:(id:string)=>string}){const now=Date.now(),soon=expiringSoon(rows,now);if(!soon.length)return null;return <article className="panel expiry-panel"><div><p className="eyebrow">Renewal attention</p><h2>Licenses expiring soon</h2></div><div className="expiry-list">{soon.slice(0,8).map(row=>{const days=daysUntilExpiry(row.expires_at,now);return <span key={row.id}><strong>{clientName(row.client_id)}</strong><code>{row.license_key}</code><b>{days} day{days===1?'':'s'} left</b></span>})}</div></article>}
function PaymentSummary({rows}:{rows:Payment[]}){const methods=['Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other'];return <div className="business-kpis summary-kpis payment-summary"><Metric label="Total payments" value={rows.length} note={`${rows.filter(row=>paidStatuses.includes(row.status)).length} completed`} color="blue"/>{methods.map((method,index)=>{const methodRows=rows.filter(row=>row.method===method);return <Metric key={method} label={method} value={methodRows.length} note={`${revenueLabel(methodRows)} received`} color={['green','gold','purple','blue','orange'][index%5]}/>})}</div>}
function normalizeCurrency(value:string){return value.trim().toUpperCase()||'UNSPECIFIED'}
function money(n:number,currency='USD'){try{return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(n)}catch{return `${currency} ${n.toLocaleString('en-US',{maximumFractionDigits:0})}`}}
function revenueLabel(rows:Payment[]){const paid=rows.filter(row=>paidStatuses.includes(row.status));const totals=new Map<string,number>();paid.forEach(row=>{const currency=normalizeCurrency(row.currency);totals.set(currency,(totals.get(currency)||0)+Number(row.amount))});return totals.size?[...totals].map(([currency,total])=>money(total,currency)).join(' · '):'No completed revenue'}
function metricIcon(label:string){const value=label.toLowerCase();if(value.includes('revenue')||value.includes('balance'))return '↗';if(value.includes('payment'))return '◈';if(value.includes('client'))return '♙';if(value.includes('license'))return '◇';if(value.includes('account'))return '◎';if(value.includes('expir')||value.includes('inactive'))return '◷';if(value.includes('active'))return '●';if(value.includes('premium'))return '✦';if(value.includes('lifetime'))return '∞';if(value.includes('basic'))return '◆';return '✧'}
function Metric({label,value,note,color}:{label:string;value:string|number;note:string;color:string}){return <article className={`metric-card biz-metric ${color}`}><span className="metric-icon" aria-hidden="true">{metricIcon(label)}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Toolbar({title,subtitle,search,setSearch,filter,setFilter,options=[],action,onAction,exportType,headingRef,announcement}:{title:string;subtitle:string;search?:string;setSearch?:(v:string)=>void;filter?:string;setFilter?:(v:string)=>void;options?:string[];action?:string;onAction?:()=>void;exportType?:string;headingRef?:RefObject<HTMLHeadingElement|null>;announcement?:string}){return <div className="business-toolbar"><div><p className="eyebrow">Orion operations</p><h2 ref={headingRef} tabIndex={headingRef?-1:undefined}>{title}</h2><p className="muted" role={announcement?'status':undefined} aria-live={announcement?'polite':undefined}>{announcement?`${subtitle} ${announcement}`:subtitle}</p></div><div className="business-actions">{setSearch&&<input aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/>} {setFilter&&<select aria-label={`Filter ${title}`} value={filter} onChange={e=>setFilter(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}{exportType&&<a className="glass-button" href={`/api/business/export?type=${exportType}`}>Export CSV</a>}{onAction&&<button className="gold-button" onClick={onAction}>＋ {action}</button>}</div></div>}
function RowActions({edit,remove}:{edit?:()=>void;remove?:()=>void}){return edit||remove?<span className="row-actions">{edit&&<button onClick={edit} aria-label="Edit record">Edit</button>}{remove&&<button className="danger" onClick={remove} aria-label="Delete record">Delete</button>}</span>:null}
function ClientCard({client,licenses,payments,open,edit,remove}:{client:Client;licenses:License[];payments:Payment[];open:()=>void;edit?:()=>void;remove?:()=>void}){const paid=payments.filter(p=>paidStatuses.includes(p.status)).reduce((s,p)=>s+Number(p.amount),0);return <article className="panel client-card"><button className="client-card-main" onClick={open}><div className="client-card-top"><span className="client-avatar">{client.full_name.split(' ').map(p=>p[0]).slice(0,2).join('').toUpperCase()}</span><Status value={client.status}/></div><h3>{client.full_name}</h3><p>{client.email||client.telegram_username||'No contact added'}</p><p className="client-country">{countryFlag(client.country)} {client.country||'Country not set'}</p><div className="client-card-meta"><span><small>Plan</small>{client.plan}</span><span><small>Licenses</small>{licenses.length}</span><span><small>Portal</small><b className={client.auth_user_id?'portal-linked':'portal-unlinked'}>{client.auth_user_id?'Linked':'Not linked'}</b></span></div></button><RowActions edit={edit} remove={remove}/></article>}
function LicenseTable({rows,clientName,edit,remove}:{rows:License[];clientName:(id:string)=>string;edit?:(r:License)=>void;remove?:(r:License)=>void}){return <article className="panel table-panel full business-table"><div className="data-table"><div className="table-head license-head"><span>Client</span><span>License</span><span>Platform</span><span>Account</span><span>Expiry</span><span>Status</span><span>Actions</span></div>{rows.map(r=><div className="table-row license-row" key={r.id}><strong>{clientName(r.client_id)}</strong><code>{r.license_key}</code><span>{r.platform}</span><span>{r.account_number||'—'}</span><time>{r.expires_at?new Date(`${r.expires_at.slice(0,10)}T00:00:00`).toLocaleDateString():'Lifetime'}</time><Status value={licenseStatus(r)}/><RowActions edit={edit?()=>edit(r):undefined} remove={remove?()=>remove(r):undefined}/></div>)}{!rows.length&&<Empty text="No licenses match this search or filter."/>}</div></article>}
function PaymentTable({rows,clientName,licenseKey=()=> '—',edit,remove,compact=false}:{rows:Payment[];clientName:(id:string)=>string;licenseKey?:(id?:string)=>string;edit?:(r:Payment)=>void;remove?:(r:Payment)=>void;compact?:boolean}){return <article className={`panel table-panel full business-table ${compact?'compact':''}`}><div className="data-table"><div className="table-head payment-head"><span>Client</span><span>Plan</span><span>License</span><span>Method</span><span>Amount</span><span>Date</span><span>Receipt</span><span>Status</span><span>Actions</span></div>{rows.map(r=><div className="table-row payment-row" key={r.id}><strong>{clientName(r.client_id)}</strong><span>{r.plan||'—'}</span><code>{licenseKey(r.license_id)}</code><span>{r.method}</span><span>{r.currency} {Number(r.amount).toLocaleString()}</span><time>{r.payment_date?new Date(`${r.payment_date}T00:00:00`).toLocaleDateString():'—'}</time>{r.receipt_number?<a className="receipt-link" href={`/receipt/${r.id}`}>{r.receipt_number}</a>:<span>—</span>}<Status value={r.status}/><RowActions edit={edit?()=>edit(r):undefined} remove={remove?()=>remove(r):undefined}/></div>)}{!rows.length&&<Empty text="No payments match this search or filter."/>}</div></article>}
function ActivityList({rows,clientName,embedded=false}:{rows:Activity[];clientName:(id:string)=>string;embedded?:boolean}){const body=<div className="activity-list">{rows.map(r=><div className="activity-item" key={r.id}><i/><div><strong>{r.action}</strong><span>{clientName(r.client_id)} · {r.details||'Record updated'}</span><small>{new Date(r.created_at).toLocaleString()} {r.actor_email?`· ${r.actor_email}`:''}</small></div></div>)}{!rows.length&&<Empty text="No activity recorded yet."/>}</div>;return embedded?body:<article className="panel activity-panel">{body}</article>}
function Status({value}:{value:string}){return <span className={`record-status ${value.toLowerCase().replace(/\s/g,'-')}`}>{value}</span>}
function Empty({text}:{text:string}){return <p className="empty-state business-empty">{text}</p>}

function ClientProfile({client,licenses,payments,activity,canWrite,close,edit,remove,invite,addLicense,addPayment,editRecord,removeRecord}:{client:Client;licenses:License[];payments:Payment[];activity:Activity[];canWrite:boolean;close:()=>void;edit:()=>void;remove:()=>void;invite:()=>void;addLicense:()=>void;addPayment:()=>void;editRecord:(t:Resource,r:RecordValue)=>void;removeRecord:(t:Resource,r:RecordValue)=>void}){const closeButton=useRef<HTMLButtonElement>(null);useEffect(()=>{const opener=document.activeElement instanceof HTMLElement?document.activeElement:null;closeButton.current?.focus();return()=>opener?.focus()},[]);return <div className="modal-backdrop" onMouseDown={close}><section className="profile-drawer" role="dialog" aria-modal="true" aria-labelledby="client-profile-title" onKeyDown={event=>handleDialogKeyDown(event,close)} onMouseDown={e=>e.stopPropagation()}><button ref={closeButton} type="button" className="modal-close" aria-label="Close client profile" onClick={close}>×</button><div className="profile-hero"><span className="client-avatar large">{client.full_name.slice(0,2).toUpperCase()}</span><div><p className="eyebrow">Client profile</p><h2 id="client-profile-title">{client.full_name}</h2><p>{client.email||'No email'} · {client.country||'Country not set'}</p></div><Status value={client.status}/></div><div className="profile-facts"><span><small>Plan</small>{client.plan}</span><span><small>Portal access</small><b className={client.auth_user_id?'portal-linked':'portal-unlinked'}>{client.auth_user_id?'Linked':'Not linked'}</b></span><span><small>Phone</small>{client.phone||'—'}</span><span><small>Joined</small>{new Date(client.created_at).toLocaleDateString()}</span></div>{canWrite&&<div className="profile-actions"><button className="glass-button" onClick={edit}>Edit client</button>{!client.auth_user_id&&<button className="invite-button" onClick={invite}>✉ Invite to portal</button>}<button className="gold-button" onClick={addLicense}>＋ License</button><button className="glass-button" onClick={addPayment}>＋ Payment</button><button className="danger-button" onClick={remove}>Delete client</button></div>}<Client360Panel clientId={client.id} canWrite={canWrite}/><h3>Licenses</h3><LicenseTable rows={licenses} clientName={()=>client.full_name} edit={canWrite?r=>editRecord('license',r):undefined} remove={canWrite?r=>removeRecord('license',r):undefined}/><h3>Payments</h3><PaymentTable rows={payments} clientName={()=>client.full_name} edit={canWrite?r=>editRecord('payment',r):undefined} remove={canWrite?r=>removeRecord('payment',r):undefined}/><h3>Activity timeline</h3><ActivityList rows={activity} clientName={()=>client.full_name} embedded/></section></div>}

function RecordModal({type,record,client,clients,licenses,close,saved}:{type:Resource;record?:RecordValue;client?:Client;clients:Client[];licenses:License[];close:()=>void;saved:()=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState('');const closeButton=useRef<HTMLButtonElement>(null);const editing=Boolean(record),titleId=`record-modal-title-${type}`;useEffect(()=>{const opener=document.activeElement instanceof HTMLElement?document.activeElement:null;closeButton.current?.focus();return()=>opener?.focus()},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const data=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch('/api/business',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resource:type,id:record?.id,data})});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p.error||'Unable to save');setSaving(false);return}await saved()}return <div className="modal-backdrop" onMouseDown={close}><form className="record-modal" role="dialog" aria-modal="true" aria-labelledby={titleId} aria-busy={saving} onKeyDown={event=>handleDialogKeyDown(event,close)} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button ref={closeButton} type="button" className="modal-close" aria-label={`Close ${type} form`} onClick={close}>×</button><p className="eyebrow">{editing?'Edit':'New'} {type}</p><h2 id={titleId}>{editing?'Update record':type==='client'?'Add a client':type==='license'?'Generate a license':'Record a payment'}</h2>{type==='client'?<ClientFields value={record as Client}/>:type==='license'?<LicenseFields clients={clients} selected={client} value={record as License}/>:<PaymentFields clients={clients} licenses={licenses} selected={client} value={record as Payment}/>} {error&&<p className="form-error" role="alert">{error}</p>}<button className="gold-button modal-submit" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Save record'}</button></form></div>}
function ClientFields({value}:{value?:Client}){return <div className="form-grid"><Field label="Full name" name="full_name" required value={value?.full_name}/><Field label="Email" name="email" type="email" value={value?.email}/><Field label="Telegram username" name="telegram_username" value={value?.telegram_username}/><Field label="Phone" name="phone" value={value?.phone}/><Field label="Country" name="country" value={value?.country}/><Select label="Plan" name="plan" options={['Free','Basic','Premium','Lifetime']} value={value?.plan}/><Select label="Status" name="status" options={['Pending','Active','Expired','Suspended']} value={value?.status}/><label className="wide"><span>Supabase Auth user UUID</span><input name="auth_user_id" defaultValue={value?.auth_user_id}/><small>Self-registered and invited accounts are linked automatically.</small></label><label className="wide"><span>Notes</span><textarea name="notes" rows={4} defaultValue={value?.notes}/></label></div>}
function LicenseFields({clients,selected,value}:{clients:Client[];selected?:Client;value?:License}){return <div className="form-grid"><ClientSelect clients={clients} selectedId={value?.client_id||selected?.id}/><Field label="License key" name="license_key" value={value?.license_key||`ORN-${crypto.randomUUID().slice(0,8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`} required/><Select label="Platform" name="platform" options={['MT5','MT4']} value={value?.platform}/><Field label="Account number" name="account_number" value={value?.account_number}/><Select label="Plan" name="plan" options={['Basic','Premium','Lifetime']} value={value?.plan}/><Select label="Status" name="status" options={['Active','Expired','Suspended']} value={value?.status}/><Field label="Expiry date" name="expires_at" type="date" value={value?.expires_at?.slice(0,10)}/></div>}
function PaymentFields({clients,licenses,selected,value}:{clients:Client[];licenses:License[];selected?:Client;value?:Payment}){const [clientId,setClientId]=useState(value?.client_id||selected?.id||clients[0]?.id||'');const [licenseId,setLicenseId]=useState(value?.license_id||'');const [plan,setPlan]=useState(value?.plan||clients.find(c=>c.id===clientId)?.plan||'Basic');const eligible=licenses.filter(l=>l.client_id===clientId);function chooseLicense(id:string){setLicenseId(id);const license=licenses.find(l=>l.id===id);if(license)setPlan(license.plan)}return <div className="form-grid"><ClientSelect clients={clients} selectedId={clientId} onChange={id=>{setClientId(id);setLicenseId('');setPlan(clients.find(c=>c.id===id)?.plan||'Basic')}}/><label><span>Purchased plan</span><select name="plan" value={plan} onChange={e=>setPlan(e.target.value)}>{['Basic','Premium','Lifetime'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Related license (optional)</span><select name="license_id" value={licenseId} onChange={e=>chooseLicense(e.target.value)}><option value="">No linked license</option>{eligible.map(l=><option key={l.id} value={l.id}>{l.license_key} · {l.platform} · {l.plan}</option>)}</select></label><Select label="Payment method" name="method" options={['Crypto','Bank Transfer','Card','PayPal','Wise','Skrill','Cash','Other']} value={value?.method}/><Select label="Payment status" name="status" options={['Pending','Paid','Manually verified','Failed','Refunded','Disputed']} value={value?.status}/><Field label="Amount" name="amount" type="number" value={String(value?.amount??0)} required/><Field label="Currency" name="currency" value={value?.currency||'USD'} required/><Field label="Payment date" name="payment_date" type="date" value={value?.payment_date?.slice(0,10)}/><Field label="Transaction / reference ID" name="reference_id" value={value?.reference_id}/><label className="wide"><span>Notes</span><textarea name="notes" rows={3} defaultValue={value?.notes}/></label></div>}
function ClientSelect({clients,selectedId,onChange}:{clients:Client[];selectedId?:string;onChange?:(id:string)=>void}){return <label className="wide"><span>Client</span><select name="client_id" value={onChange?selectedId:undefined} defaultValue={onChange?undefined:selectedId} onChange={e=>onChange?.(e.target.value)} required>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label>}
function Field({label,name,type='text',required=false,value}:{label:string;name:string;type?:string;required?:boolean;value?:string}){return <label><span>{label}</span><input name={name} type={type} required={required} defaultValue={value} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined}/></label>}
function Select({label,name,options,value}:{label:string;name:string;options:string[];value?:string}){return <label><span>{label}</span><select name={name} defaultValue={value}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
