'use client';

import { FormEvent, useCallback, useEffect, useState, type CSSProperties } from 'react';
import ClientAvatar from '@/components/client-avatar';
import type { ClientProfile } from '@/lib/client-profile';
import styles from './client-360.module.css';

type AdminProfile=ClientProfile&{updatedAt:string|null;linked:boolean;available:boolean;visible:boolean};
type Data={client:{full_name:string;email?:string|null;country?:string|null;notes?:string|null};profile:AdminProfile;health:{score:number;label:string;tone:string;reasons:string[]};timeline:{id:string;title:string;detail:string;date:string;tone:string}[];reminders:{id:string;title:string;notes?:string;due_at:string;status:string}[];communications:{id:string;channel:string;direction:string;subject:string;body?:string;occurred_at:string}[]};

export default function Client360Panel({clientId,canWrite}:{clientId:string;canWrite:boolean}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState<'profile'|'timeline'|'reminders'|'communications'|'notes'>(canWrite?'profile':'timeline'),[form,setForm]=useState<'reminder'|'communication'|null>(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/client-360/${clientId}`,{cache:'no-store'}),payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(payload?.error||'Client 360 is unavailable.');setData(payload)}catch(reason){setError(reason instanceof Error?reason.message:'Client 360 is unavailable.')}finally{setLoading(false)}},[clientId]);
 useEffect(()=>{void load()},[load]);
 async function write(payload:Record<string,unknown>){setSaving(true);setError('');setNotice('');try{const response=await fetch(`/api/client-360/${clientId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error||'Unable to save.');setForm(null);setNotice('Client 360 updated.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save.')}finally{setSaving(false)}}
 function submitReminder(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget),dueAt=isoDateTime(values.get('due_at'));if(!dueAt){setError('Choose a valid reminder date and time.');return}void write({action:'create-reminder',title:values.get('title'),notes:values.get('notes'),due_at:dueAt})}
 function submitCommunication(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget),occurredAt=isoDateTime(values.get('occurred_at'));if(!occurredAt){setError('Choose a valid communication date and time.');return}void write({action:'add-communication',channel:values.get('channel'),direction:values.get('direction'),subject:values.get('subject'),body:values.get('body'),occurred_at:occurredAt})}
 if(loading)return <section className={styles.shell}><p className={styles.loading} role="status">Building the Client 360 timeline…</p></section>;
 if(error&&!data)return <section className={styles.shell}><p className={styles.error} role="alert">{error}</p></section>;
 if(!data)return null;
 const healthColor=data.health.tone==='green'?'#39f28a':data.health.tone==='gold'?'#f6c453':data.health.tone==='orange'?'#ff9f43':'#ff566d';
 const healthStyle={'--health-score':data.health.score,'--health-color':healthColor} as CSSProperties;
 return <section className={styles.shell} aria-labelledby="client-360-title"><header className={styles.header}><div><p className="eyebrow">Client 360°</p><h3 id="client-360-title">Operational health and history</h3></div><div className={styles.health} style={healthStyle} aria-label={`${data.health.score} out of 100, ${data.health.label}`}><strong>{data.health.score}</strong><small>{data.health.label}</small></div></header><ul className={styles.healthReasons}>{data.health.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>
  <nav className={styles.tabs} aria-label="Client 360 sections">{((data.profile.visible?['profile','timeline','reminders','communications','notes']:['timeline','reminders','communications','notes']) as Array<'profile'|'timeline'|'reminders'|'communications'|'notes'>).map(value=><button type="button" data-active={tab===value} aria-pressed={tab===value} onClick={()=>setTab(value)} key={value}>{value[0].toUpperCase()+value.slice(1)}</button>)}</nav>
  {notice&&<p className={styles.notice} role="status">{notice}</p>}{error&&<p className={styles.formError} role="alert">{error}</p>}
  {tab==='profile'&&data.profile.visible&&<AdminPortalProfile client={data.client} profile={data.profile}/>}
  {tab==='timeline'&&(data.timeline.length?<ol className={styles.timeline}>{data.timeline.map(item=><li className={styles.event} data-tone={item.tone} key={item.id}><i aria-hidden="true"/><div><strong>{item.title}</strong><span>{item.detail}</span></div><time dateTime={item.date}>{new Date(item.date).toLocaleString()}</time></li>)}</ol>:<p className={styles.empty}>No timeline records yet.</p>)}
  {tab==='reminders'&&<><div className={styles.toolbar}><span/>{canWrite&&<button type="button" onClick={()=>setForm(form==='reminder'?null:'reminder')}>＋ Reminder</button>}</div>{form==='reminder'&&<form className={styles.form} onSubmit={submitReminder}><label><span>Title</span><input name="title" required maxLength={180}/></label><label><span>Due date</span><input name="due_at" type="datetime-local" required/></label><label className={styles.wide}><span>Notes</span><textarea name="notes" maxLength={1000}/></label><button className={styles.wide} disabled={saving}>{saving?'Saving…':'Save reminder'}</button></form>}<ul className={styles.list}>{data.reminders.map(item=><li className={styles.item} key={item.id}><div><strong>{item.title}</strong><time>{new Date(item.due_at).toLocaleString()}</time>{item.notes&&<p>{item.notes}</p>}<span>{item.status}</span></div>{canWrite&&item.status==='Open'&&<button type="button" onClick={()=>void write({action:'set-reminder-status',reminder_id:item.id,status:'Done'})}>Mark done</button>}</li>)}</ul>{!data.reminders.length&&<p className={styles.empty}>No admin reminders.</p>}</>}
  {tab==='communications'&&<><div className={styles.toolbar}><span/>{canWrite&&<button type="button" onClick={()=>setForm(form==='communication'?null:'communication')}>＋ Log communication</button>}</div>{form==='communication'&&<form className={styles.form} onSubmit={submitCommunication}><label><span>Channel</span><select name="channel"><option>Email</option><option>Telegram</option><option>Phone</option><option>Portal</option><option>Other</option></select></label><label><span>Direction</span><select name="direction"><option>Outbound</option><option>Inbound</option><option>Internal</option></select></label><label><span>Subject</span><input name="subject" required maxLength={180}/></label><label><span>Date and time</span><input name="occurred_at" type="datetime-local" required/></label><label className={styles.wide}><span>Details</span><textarea name="body" maxLength={4000}/></label><button className={styles.wide} disabled={saving}>{saving?'Saving…':'Log communication'}</button></form>}<ul className={styles.list}>{data.communications.map(item=><li className={styles.item} key={item.id}><div><strong>{item.subject}</strong><span>{item.channel} · {item.direction}</span>{item.body&&<p>{item.body}</p>}<time>{new Date(item.occurred_at).toLocaleString()}</time></div></li>)}</ul>{!data.communications.length&&<p className={styles.empty}>No communication history recorded.</p>}</>}
  {tab==='notes'&&<form className={styles.notes} onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);void write({action:'update-notes',notes:values.get('notes')})}}><textarea name="notes" defaultValue={data.client.notes||''} maxLength={2000} aria-label="Internal client notes" disabled={!canWrite}/>{canWrite&&<button disabled={saving}>{saving?'Saving…':'Save internal notes'}</button>}</form>}
 </section>
}

function AdminPortalProfile({client,profile}:{client:Data['client'];profile:AdminProfile}){
 const completed=Boolean(profile.updatedAt),displayName=profile.nickname||client.full_name;
 return <section className={styles.portalProfile} aria-labelledby="admin-portal-profile-title">
  <div className={styles.profileIdentity}><ClientAvatar avatarKey={profile.avatarKey} size="large"/><div><small>Client-selected identity</small><h4 id="admin-portal-profile-title">{displayName}</h4><p>{client.full_name}{client.country?` · ${client.country}`:''}</p></div><span data-complete={completed}>{completed?'Profile updated':profile.linked?'Not completed':'Portal not linked'}</span></div>
  {!profile.available&&<p className={styles.profileWarning} role="status">Portal preferences are temporarily unavailable. Contact details below are still current.</p>}
  <div className={styles.profileFacts}><span><small>Nickname</small><strong>{profile.nickname||'Not added'}</strong></span><span><small>Telegram</small><strong>{profile.telegramUsername?`@${profile.telegramUsername}`:'Not added'}</strong></span><span><small>Phone</small><strong>{profile.phoneNumber||'Not added'}</strong></span><span><small>Last profile update</small><strong>{profile.updatedAt?new Date(profile.updatedAt).toLocaleString():'No client update yet'}</strong></span></div>
  <div className={styles.profileBio}><small>Trading bio</small><p>{profile.bio||'The client has not added a trading bio.'}</p></div>
  <div className={styles.profilePreferences}><ProfileValues label="Brokers used" values={profile.brokers}/><ProfileValues label="Most-traded markets" values={profile.tradingPairs}/></div>
  <p className={styles.profilePrivacy}>Client-provided portal preferences. These details do not change plan, license, payment, or account status.</p>
 </section>
}

function ProfileValues({label,values}:{label:string;values:string[]}){return <div><small>{label}</small><span>{values.length?values.map(value=><i key={value}>{value}</i>):<b>None selected</b>}</span></div>}

function isoDateTime(value:FormDataEntryValue|null){const date=new Date(String(value||''));return Number.isNaN(date.getTime())?null:date.toISOString()}
