'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type Release = { id:string; version:string; title:string; release_notes?:string; platform:'MT4'|'MT5'|'Both'; download_url?:string; published:boolean; released_at:string };

export default function ReleaseManager({canWrite}:{canWrite:boolean}) {
  const [rows,setRows]=useState<Release[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[modal,setModal]=useState<Release|null|undefined>(undefined);
  const load=useCallback(async()=>{setLoading(true);const response=await fetch('/api/releases',{cache:'no-store'});const body=await response.json().catch(()=>null);if(response.ok){setRows(body);setError('')}else setError(body?.error||'Unable to load releases');setLoading(false)},[]);
  useEffect(()=>{load()},[load]);
  const visible=useMemo(()=>rows.filter(row=>(filter==='All'||row.platform===filter||(filter==='Published'&&row.published)||(filter==='Draft'&&!row.published))&&`${row.version} ${row.title} ${row.platform} ${row.release_notes||''}`.toLowerCase().includes(search.toLowerCase().trim())),[rows,search,filter]);
  async function remove(row:Release){if(!confirm(`Delete Orion ${row.version}? Clients will immediately lose access to this release.`))return;const response=await fetch('/api/releases',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:row.id})});const body=await response.json().catch(()=>null);if(!response.ok){alert(body?.error||'Unable to delete release');return}await load()}
  if(loading)return <div className="business-loading"><span/>Loading product releases…</div>;
  if(error)return <article className="panel migration-notice"><p className="eyebrow">Release manager unavailable</p><h2>Check the client portal database setup</h2><p className="muted">{error}</p></article>;
  return <><div className="business-toolbar"><div><p className="eyebrow">Product delivery</p><h2>Downloads & releases</h2><p className="muted">Publish secure MT4 and MT5 downloads to client accounts.</p></div><div className="business-actions"><input aria-label="Search releases" placeholder="Search versions or titles…" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Filter releases" value={filter} onChange={event=>setFilter(event.target.value)}>{['All','Published','Draft','MT4','MT5','Both'].map(value=><option key={value}>{value}</option>)}</select>{canWrite&&<button className="gold-button" onClick={()=>setModal(null)}>＋ New release</button>}</div></div><div className="business-kpis release-kpis"><ReleaseMetric label="Total releases" value={rows.length}/><ReleaseMetric label="Published" value={rows.filter(row=>row.published).length}/><ReleaseMetric label="Drafts" value={rows.filter(row=>!row.published).length}/><ReleaseMetric label="Latest version" value={rows[0]?.version||'—'}/></div><div className="release-grid">{visible.map(row=><article className="panel release-card" key={row.id}><div className="release-card-head"><span className={`record-status ${row.published?'active':'pending'}`}>{row.published?'Published':'Draft'}</span><span className="release-platform">{row.platform}</span></div><p className="eyebrow">Version {row.version}</p><h3>{row.title}</h3><p>{row.release_notes||'No release notes added.'}</p><div className="release-card-foot"><time>{new Date(row.released_at).toLocaleDateString()}</time><span>{row.download_url?'Download connected':'No download URL'}</span></div>{canWrite&&<div className="row-actions release-actions"><button onClick={()=>setModal(row)}>Edit</button><button className="danger" onClick={()=>remove(row)}>Delete</button></div>}</article>)}{!visible.length&&<p className="empty-state business-empty">No releases match this search or filter.</p>}</div>{modal!==undefined&&<ReleaseModal value={modal||undefined} close={()=>setModal(undefined)} saved={async()=>{setModal(undefined);await load()}}/>}</>;
}

function ReleaseMetric({label,value}:{label:string;value:string|number}){return <article className="metric-card biz-metric blue"><span className="metric-icon">⬇</span><p>{label}</p><strong>{value}</strong><small>Client portal delivery</small></article>}
function ReleaseModal({value,close,saved}:{value?:Release;close:()=>void;saved:()=>void}){const[saving,setSaving]=useState(false),[error,setError]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget).entries());const data={...values,published:values.published==='on'};const response=await fetch('/api/releases',{method:value?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value?{id:value.id,data}:data)});const body=await response.json().catch(()=>null);if(!response.ok){setError(body?.error||'Unable to save release');setSaving(false);return}await saved()}return <div className="modal-backdrop" onMouseDown={close}><form className="record-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">{value?'Edit release':'New release'}</p><h2>{value?'Update product download':'Publish an Orion version'}</h2><div className="form-grid"><label><span>Version</span><input name="version" required maxLength={40} defaultValue={value?.version} placeholder="2.1.0"/></label><label><span>Platform</span><select name="platform" defaultValue={value?.platform||'MT5'}><option>MT5</option><option>MT4</option><option>Both</option></select></label><label className="wide"><span>Release title</span><input name="title" required maxLength={140} defaultValue={value?.title} placeholder="Orion Scalper 2.1"/></label><label className="wide"><span>HTTPS download URL</span><input name="download_url" type="url" defaultValue={value?.download_url} placeholder="https://downloads.example.com/orion.zip"/></label><label className="wide"><span>Release notes</span><textarea name="release_notes" rows={6} maxLength={4000} defaultValue={value?.release_notes}/></label><label className="release-publish wide"><input name="published" type="checkbox" defaultChecked={value?.published}/><span>Publish immediately to eligible client portals</span></label></div>{error&&<p className="form-error">{error}</p>}<button className="gold-button modal-submit" disabled={saving}>{saving?'Saving…':value?'Save changes':'Create release'}</button></form></div>}
